version: "3.6"
services:
  db:
    image: mysql:8.0.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    depends_on:
      - db
    image: adminer
    restart: unless-stopped
    ports:
    - ${ADMINER_LOCAL_PORT}:${ADMINER_DOCKER_PORT}
    networks:
      - mysql-compose-network
    environment:
      - ADMINER_DESIGN=$ADMINER_DESIGN
  app:
    depends_on:
      - adminer
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.javax.persistence.schema-generation.scripts.action" : "create",
        "spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target" : "sql/create.sql",
        "spring.jpa.properties.javax.persistence.schema-generation.scripts.create-source":"metadata",
        "server.port":"$SPRING_DOCKER_PORT",
        "springdoc.api-docs.path":"/docs/apidoc",
        "springdoc.swagger-ui.path":"/docs/swagger-ui"
       }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge

volumes:
  db:
